### ISSUE TITLE
mysterious argument error

### ISSUE THREAD

**Issue by jimmac** [ggreer/jekyll-gallery-generator#42]
Has been a while since I've generated photos. rmagic seems to successfully generate the thumbnails, but then I get this argment error:

```
$ bundle exec jekyll s --trace
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Configuration file: /var/home/jimmac/public_html/photos/_config.yml
            Source: /var/home/jimmac/public_html/photos
       Destination: /var/home/jimmac/public_html/photos/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
bundler: failed to load command: jekyll (/var/home/jimmac/bin/jekyll)
ArgumentError: comparison of Jekyll::GalleryPage with Jekyll::GalleryPage failed
  /var/home/jimmac/public_html/photos/_plugins/gallery-generator.rb:29:in `sort!'
  /var/home/jimmac/public_html/photos/_plugins/gallery-generator.rb:29:in `initialize'
  /var/home/jimmac/public_html/photos/_plugins/gallery-generator.rb:169:in `new'
  /var/home/jimmac/public_html/photos/_plugins/gallery-generator.rb:169:in `generate'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/site.rb:185:in `block in generate'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `each'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `generate'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/site.rb:75:in `process'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
  /var/home/jimmac/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /var/home/jimmac/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /var/home/jimmac/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /var/home/jimmac/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /var/home/jimmac/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /var/home/jimmac/.gem/ruby/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
  /var/home/jimmac/bin/jekyll:23:in `load'
  /var/home/jimmac/bin/jekyll:23:in `<top (required)>'
```

**Comment by jimmac** [comment]
Turns out it's due to the mismatch of galleries config and the directroy names.
